spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?serverTimezone=Asia/Seoul
    username: root         # 본인 MySQL 사용자 계정
    password:      # 본인 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # 개발용: 테이블 자동 생성/업데이트
    show-sql: true         # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true   # SQL 보기 좋게 정렬

  h2:
    console:
      enabled: false       # H2 안 쓸 거니까 비활성화

server:
  port: 8080               # 포트 번호 (기본값)

logging:
  level:
    org.hibernate.SQL: debug